imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: doctrine.yml }
    - { resource: maintenance.yml }
#    - { resource: "@McMaklerBundle/Resources/config/services.yml" }

framework:
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    http_method_override: true

twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

fos_rest:
    view:
        view_response_listener: 'force'
        failed_validation: HTTP_BAD_REQUEST
        default_engine: php
        mime_types:
            json: ['application/json; charset=UTF-8', 'application/json']
        formats:
            json: true
            xml: false
            rss: false
    format_listener: ~
    body_listener:
        decoders:
            json: fos_rest.decoder.json
            xml: fos_rest.decoder.xml
    param_fetcher_listener: true
    allowed_methods_listener: true
    serializer:
        serialize_null: true

sensio_framework_extra:
    view:
        annotations: true

jms_serializer:
    visitors:
        json:
            options: JSON_UNESCAPED_UNICODE

services:
    api_formatter:
        class: Monolog\Formatter\JsonFormatter
    text_formatter:
        class: Monolog\Formatter\LineFormatter

monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
            nested:
                type:  rotating_file
                path:  "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                max_files: 10
            nasa_neo:
                type: rotating_file
                path: "%kernel.logs_dir%/nasa_neo.log"
                level: debug
                channels: [nasa_neo]
                formatter: api_formatter
                max_files: 10
        channels: [nasa_neo]