lexik_maintenance:
    authorized:
        ips: %allowed_ips_during_maintenance%                                      
    driver:      
        ttl: 3600                                                                  
        class: '\Lexik\Bundle\MaintenanceBundle\Drivers\FileDriver'                
        options: {file_path: %kernel.root_dir%/cache/lock}                         

    #Optional. response code and status of the maintenance page
    response:
        code: 503 
        status: "Service Temporarily Unavailable"