<?php

namespace McMaklerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NeoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NeoRepository extends EntityRepository
{
}
